baseurl: /alt-notify/
highlighter: pygments
markdown: kramdown
permalink: date
maruku:
    use_tex:    false
    use_divs:   false
    png_engine: blahtex
    png_dir:    images/latex
    png_url:    /images/latex

gems:
    - jekyll-sitemap

defaults:
    -
      scope:
          path: ""
      values:
          sitemap: false
          # couldn't access site.basetitle (seeabove)
          # in a page, so..
          project_name: 'alt-notify'
          #
          project_description: 'Alerts, notification, whatever for Alt.'
          #
          project_repo: https://github.com/sourcescript/alt-notify

exclude: ['LICENSE', 'README.md']
